services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: production
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - management
      - simulation
    environment:
      # - HOST=0.0.0.0
      - VITE_SIMULATION_URL=http://localhost:4000
      - VITE_MANAGEMENT_URL=http://localhost:3000
    networks:
      - app-network

  management:
    build:
      context: .
      dockerfile: apps/management/Dockerfile
      target: production
    container_name: management
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - kafka
    environment:
      # - HOST=0.0.0.0
      - PORT=3000
      - JWT_SECRET=fhdksjfbdhsjb34873298
      - JWT_EXPIRES_IN=36000000
      - MONGO_URI=mongodb://mongo:27017/test
      - DATABASE_URL=mongodb://mongo:27017
      - DATABASE_NAME=test
      - KAFKA_BROKER=kafka:9093
    networks:
      - app-network

  simulation:
    build:
      context: .
      dockerfile: apps/simulation/Dockerfile
      target: production
    container_name: simulation
    hostname: simulation
    depends_on:
      - mongo
      - kafka
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=mongodb://mongo:27017
      - DATABASE_NAME=test
      - KAFKA_BROKER=kafka:9093
    networks:
      - app-network
    ports:
      - "4000:3000"

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    ports:
      - "27017:27017"

  kafka:
    image: apache/kafka-native
    hostname: kafka
    container_name: kafka
    depends_on:
      - kafka-ui
    ports:
      - "9092:9092"
    networks:
      - app-network
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: kafbat/kafka-ui:main
    container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
